version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
    image:
      orienteer:latest
    volumes:
      - .:/app
    env_file:
      - .env
    command: python -m orienteer.api
    ports:
      - "8080:8080"

  bot:
    container_name: bot
    build:
      context: .
    image:
      orienteer:latest
    volumes:
      - .:/app
    env_file:
      - .env
    command: python -m orienteer.bot

  checker:
    container_name: checker
    build:
      context: .
    image:
      orienteer:latest
    volumes:
      - .:/app
    env_file:
      - .env
    command: python -m orienteer.checker