services:
  api:
    container_name: api
    build:
      context: .
    image:
      orienteer:latest
    volumes:
      - .:/app
    env_file:
      - .env
    command: python -m orienteer.api
    ports:
      - "8080:8080"
    restart: unless-stopped

  bot:
    container_name: bot
    build:
      context: .
    image:
      orienteer:latest
    volumes:
      - .:/app
    env_file:
      - .env
    command: python -m orienteer.bot
    restart: unless-stopped

  checker:
    container_name: checker
    build:
      context: .
    image:
      orienteer:latest
    volumes:
      - .:/app
    env_file:
      - .env
    command: python -m orienteer.checker
    restart: unless-stopped
