version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PORT: ${POSTGRES_ORIENTEER_PORT}
      POSTGRES_DBNAME: ${POSTGRES_ORIENTEER_DBNAME}
      POSTGRES_USER: ${POSTGRES_ORIENTEER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ORIENTEER_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
